### PR TITLE
Fix typos in docstring links to Elasticsearch documentation.

### PR DESCRIPTION
**Pull request by magnusbaeck**

### CODE REVIEW

**Comment by HonzaKral** [comment]
Thank you for the patch, could I please ask you to sign our [Contributor License Agreement](http://www.elasticsearch.org/contributor-agreement/) so that I can merge it?

Thanks!

**Comment by magnusbaeck** [comment]
My employer (Sony Mobile) has signed a corporate CLA and per instructions from Elasticsearch I also signed an individual CLA on Oct 6, 2014. I've dug up my CLA and checked that it lists the correct Github username and that the email address matches my commit. I'm not sure I can debug this further on my end.

**Comment by HonzaKral** [comment]
Ah ok, thanks for the information, and sorry about the hassle - the API provided by the e-signing provider has some gaps, we are looking into it. I appreciate your patience with the process.

**Comment by HonzaKral** [comment]
Closed via 919b8f5ce30e4628ce249c4c4d68782a0bf1c2fa

**Pull request closed without merging**
